# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6b6c30960d470b9934f87ac7851bfe078545a9d336b183ac0abad5d7dad5d9b87f448f7e2ab557c833b09e9af21215e72f122ac1526d1cedb5e3e9ed70c9b7

test:
  secret_key_base: 898a4ed2ff0ed007584cc990332fb289887cce13571cd31b70c4b1721a18925192fdef028860be191cb2f9435c2bfabe4ed8a2224840d1ffc99aa3980197667a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
